spring:
  application:
    name: store
  datasource:
    url: jdbc:mysql://localhost:3306/store_api?createDatabaseIfNotExist=true
    username: root
    password: huyanh2003
  jpa:
    show-sql: true

server:
  port: 8001